### ISSUE TITLE
你好，请问能解释一下数据中frequency列的计算过程吗？

### ISSUE THREAD

**Issue by slothydog** [zwtywwq/mg2vec#1]
last column is the frequency of the metagraph instances appearing with the two nodes (staring with f).

**Comment by zwtywwq** [comment]
To generate the metagraphs and corresponding instances for each dataset, see http://www.yfang.site/data-and-tools/grami-with-automorphism and http://www.yfang.site/data-and-tools/submatch for detailed information.
